config/routes.rb
Thisversusthat::Application.routes.draw do
  resources :showdowns do
    post 'add_vote'
    resources :votes
    resources :comments
  end

  resources :topics do
    resources :votes
  end

  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "home#index"
  devise_for :users
  resources :users do
    resources :comments
  end
end

app/models/comment.rb
class Comment
  include Mongoid::Document
  field :name
  field :comment_text
  
  belongs_to :user
  
  embedded_in :showdown
  
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_filter :find_showdown

  # GET /topics
  # GET /topics.json
  def index
    @comments = @showdown.comments.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @comments }
    end
  end

  # GET /topics/1
  # GET /topics/1.json
  def show
    @comment = @showdown.comments.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @comment }
    end
  end

  # GET /topics/new
  # GET /topics/new.json
  def new
    
    respond_to do |format|
      format.html # new.html.erb
      format.js
      format.json { render json: @comment }
    end
  end

  # GET /topics/1/edit
  def edit
    @comment = @showdown.comments.find(params[:id])
  end

  # POST /topics
  # POST /topics.json
  def create
    #comment = @showdown.comments.new(params[:comment])

    respond_to do |format|
      if @showdown.comments.create!(params[:comment])
        format.html { redirect_to @comment, notice: 'Comment was successfully created.' }
        format.js
        format.json { render json: @comment, status: :created, location: @comment }
      else
        format.html { render action: "new" }
        format.js
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /topics/1
  # PUT /topics/1.json
  def update
    @comment = @showdown.comments.find(params[:id])

    respond_to do |format|
      if @comment.update_attributes(params[:topic])
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /topics/1
  # DELETE /topics/1.json
  def destroy
    @comment = @showdown.comments.find(params[:id])
    @comment.destroy

    respond_to do |format|
      format.html { redirect_to topics_url }
      format.json { head :no_content }
    end
  end
  
  private
  def find_showdown
    @showdown = Showdown.find params[:showdown_id]
  end
end

app/views/comments/_form.html.haml
= simple_form_for [showdown, comment], :html => {:multipart => true}, :remote=>true do |f|
  = f.error_notification
  = display_base_errors comment

  .field
    = f.label :comment_text
    = f.text_field :comment_text, :class=>'span6', :size=>140

  .actions
    = f.submit 'Save'

app/views/comments/_index.html.haml
= render :partial=>'comments/list_comments', :locals=>{:comments=>comments}

app/views/comments/_list_comments.haml
- comments.each do |comment|
  %b= comment.user.name rescue 'anon'
  %p= comment.comment_text

app/views/comments/_new.html.haml
%h1 Add comment

= render 'form'

app/views/comments/_show_comments.haml
- unless showdown.comments.blank?
    %p
    = render :partial=>'comments/list_comments', :locals=>{:comments=>showdown.comments}

app/views/comments/create.js.erb
$('.show_comments').html("<%=j render :partial=>'comments/show_comments', :locals=>{:showdown=>@showdown} %>");
$('.add_comment').html('')

app/views/comments/edit.html.haml
%h1 Editing topic

= render 'form'

= link_to 'Show', @topic
\|
= link_to 'Back', topics_path
\|
= link_to 'Delete', @topic, method: :delete, data: { confirm: 'Are you sure?' }

app/views/comments/index.html.haml
%h1 Comments

= render :partial=>'list_comments', :locals=>{:comments=>@comments}

%br

= link_to 'New Topic', new_topic_path
\|
= link_to 'Home', root_path

app/views/comments/new.html.haml
%h4 Add comment

= render 'form'

app/views/comments/new.js.erb
$('.add_comment').html("<%=j render :partial=> 'comments/form', :locals=>{:showdown=>@showdown, :comment=>@showdown.comments.new} %>");

app/views/comments/show.html.haml
= render :partial=>"show_topic", :locals=>{:topic=>@topic}

= link_to 'List', topics_path
\|
= link_to 'Edit', edit_topic_path(@topic)
\|
= link_to 'Destroy', @topic, method: :delete, data: { confirm: 'Are you sure?' }