config/routes.rb
Thisversusthat::Application.routes.draw do
  resources :showdowns do
    post 'add_vote'
    resources :votes
    resources :comments
  end

  resources :topics do
    resources :votes
  end

  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "home#index"
  devise_for :users
  resources :users do
    resources :comments
  end
end

app/models/showdown.rb
class Showdown
  include Mongoid::Document
  field :name, type: String
  field :topic_ids, type: Array, :default=>[]
  
  #has_many :topics
  has_many :votes, :dependent=>:destroy
  embeds_many :comments
  
  def topics
    Topic.in(id: topic_ids)
  end
  
  def votes_for(topic)
    Vote.where(topic_id: topic.id, showdown_id: self.id).count
  end
end

app/controllers/showdowns_controller.rb
class ShowdownsController < ApplicationController
  # GET /showdowns
  # GET /showdowns.json
  def index
    @showdowns = Showdown.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @showdowns }
    end
  end

  # GET /showdowns/1
  # GET /showdowns/1.json
  def show
    @showdown = Showdown.find(params[:id])
    @topics = Topic.all
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @showdown }
    end
  end

  # GET /showdowns/new
  # GET /showdowns/new.json
  def new
    @showdown = Showdown.new
    @topics = Topic.all

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @showdown }
    end
  end

  # GET /showdowns/1/edit
  def edit
    @showdown = Showdown.find(params[:id])
    @topics = Topic.in(id: @showdown.topic_ids)
  end

  # POST /showdowns
  # POST /showdowns.json
  def create
    @showdown = Showdown.new(params[:showdown])
    
    if params[:topic_1]
      @showdown.topic_ids << params[:topic_1]
    end
    
    if params[:topic_2]
      @showdown.topic_ids << params[:topic_2]
    end

    respond_to do |format|
      if @showdown.save
        format.html { redirect_to @showdown, notice: 'Showdown was successfully created.' }
        format.json { render json: @showdown, status: :created, location: @showdown }
      else
        format.html { render action: "new" }
        format.json { render json: @showdown.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /showdowns/1
  # PUT /showdowns/1.json
  def update
    @showdown = Showdown.find(params[:id])
    
    if params[:topic_1]
      @showdown.topic_ids << params[:topic_1]
    end
    
    if params[:topic_2]
      @showdown.topic_ids << params[:topic_2]
    end

    respond_to do |format|
      if @showdown.update_attributes(params[:showdown])
        format.html { redirect_to @showdown, notice: 'Showdown was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @showdown.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /showdowns/1
  # DELETE /showdowns/1.json
  def destroy
    @showdown = Showdown.find(params[:id])
    @showdown.destroy

    respond_to do |format|
      format.html { redirect_to showdowns_url }
      format.json { head :no_content }
    end
  end
  
  def add_vote
    @showdown = Showdown.find(params[:showdown_id])
    
    if params[:topic_id]
      
      #todo: validate input
      topic = Topic.find(params[:topic_id])
      vote = Vote.new(:topic_id=>topic.id, :showdown_id=>@showdown.id, ip_address: request.env["REMOTE_ADDR"])
      respond_to do |format|
        if vote.save
          format.html { redirect_to @showdown, notice: 'Vote was successfully created.' }
          format.json { render json: @showdown, status: :created, location: @showdown }
        else
          msg = ""
          vote.errors.full_messages.each{|e| msg += e}
          format.html { redirect_to @showdown, notice: "Invalid vote. #{msg}" }
          format.json { render json: @showdown.errors, status: :unprocessable_entity }
        end
      end
    end
  end
end

app/helpers/showdowns_helper.rb
module ShowdownsHelper
end

app/views/showdowns/_form.html.haml
= simple_form_for @showdown do |f|
  = f.error_notification
  = display_base_errors @showdown

  .field
    = f.label :name
    = f.text_field :name
    
  .field
    = f.label "Add Topic 1"
    = select_tag "topic_1", options_from_collection_for_select(@topics, "id", "name")
    
  .field
    = f.label "Add Topic 2"
    = select_tag "topic_2", options_from_collection_for_select(@topics, "id", "name")
  .field
    = link_to "Create topic", new_topic_url
  .actions
    = f.submit 'Save'

app/views/showdowns/edit.html.haml
%h1 Editing showdown

= render 'form'

= link_to 'Show', @showdown
\|
= link_to 'Back', showdowns_path

app/views/showdowns/index.html.haml
%h1 Listing showdowns

%table
  %tr
    %th Name
    %th
    %th
    %th

  - @showdowns.each do |showdown|
    %tr
      %td= showdown.name
      %td= link_to 'Show', showdown
      %td= link_to 'Edit', edit_showdown_path(showdown)
      %td= link_to 'Destroy', showdown, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Showdown', new_showdown_path
\|
= link_to 'Home', root_path

app/views/showdowns/new.html.haml
%h1 New showdown

= render 'form'

= link_to 'Back', showdowns_path

app/views/showdowns/show.html.haml
%p
  %b Name:
  = @showdown.name
  
%table{:style=>"width:100%;"}
  %tr
    - @showdown.topics.each do |t|
      %td{:align=>"center"}
        = image_tag(t.avatar.thumb.url) if t.avatar?
        %br
        = t.name
  %tr
    - @showdown.topics.each do |t|
      %td{:align=>"center"}
        = link_to 'Vote', showdown_add_vote_path(@showdown, :topic_id=>t.id), :method=>:post
  %tr
    - @showdown.topics.each do |t|
      %td{:align=>"center"}
        = @showdown.votes_for(t)
        votes
  %tr
    %td{:colspan=>2, :align=>"center"}
      %b VS

.comment_add_link
  %b= link_to 'Add Comment', new_showdown_comment_path(@showdown), :remote=>true
.add_comment
.show_comments
  = render :partial=>'comments/show_comments', :locals=>{:showdown=>@showdown}

%p
- if false
  = link_to 'Edit', edit_showdown_path(@showdown)
  \|
  = link_to 'Back', showdowns_path
  \|
  = link_to 'Destroy', @showdown, method: :delete, data: { confirm: 'Are you sure?' }